# Generated by Django 4.1.3 on 2022-12-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_middle_name',
            field=models.BooleanField(default=True),
        ),
    ]
