# Generated by Django 4.1.3 on 2022-12-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0003_customer_privatedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatedata',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='privatedata',
            name='vat',
            field=models.CharField(default='', max_length=20),
        ),
    ]
