# Generated by Django 3.2.16 on 2024-05-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0004_alter_privatedata_age_alter_privatedata_vat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('itself', 'Itself'), ('external', 'External')], default='itself', max_length=50)),
                ('itself_uid', models.CharField(blank=True, default='', max_length=50)),
                ('external_uid', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='privatedata',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='privatedata',
            name='vat',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
